# Generated by Django 4.2.5 on 2023-09-24 21:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=30)),
                ('task_name_uz', models.CharField(default='', max_length=30, null=True)),
                ('task_name_en', models.CharField(default='', max_length=30, null=True)),
                ('task_name_ru', models.CharField(default='', max_length=30, null=True)),
                ('create', models.DateTimeField(default=datetime.datetime.now)),
                ('update', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=200)),
                ('description_uz', models.CharField(default='', max_length=200, null=True)),
                ('description_en', models.CharField(default='', max_length=200, null=True)),
                ('description_ru', models.CharField(default='', max_length=200, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trans2',
            },
        ),
    ]
